### PR TITLE
README: fix typos, reorganize headings, shorten sentences

### PR DESCRIPTION
**Pull request by Kazevic**

### CODE REVIEW

**Comment by Hydr8gon** [comment]
I hate to be picky, but I'll go over my thoughts on this:

- The tagline "A (hopefully!) speedy NDS emulator" shouldn't be treated as a sentence; it was put under the project title because it's, well, a tagline
- "Aims to be a fast, portable Nintendo DS emulator" isn't a grammatically-correct sentence; it needs an object for the verb to apply to. In general, the shortened sentences feel less natural and don't flow as well for me
- Removing contractions makes the reading feel a bit stiff and formal, and ironically goes against the idea of shortening
- On the opposite end, using "&" instead of "and" in a sentence feels way too informal
- Not having the "Overview" header looks weird to me; I feel like every block of text should have a header that describes its purpose
- "Installation" doesn't sound like an appropriate header; the releases aren't installers, they're just loose executables
- The "Building" headers being smaller makes them look out of place; I'd rather all headers be the same size, or at least have the smaller ones at the bottom so the size isn't changing back and forth
- "GBATEK addendum by Arisotura - It is not perfect, so some information came from here too" doesn't make sense; this implies that the addendum isn't perfect, and that's why I used it? GBATEK is what's imperfect, not the addendum
- Removing the empty lines between sections makes it hard to look at the raw file; I don't think it affects anything visually so I'd rather keep the spacing

Sorry if this is... a lot. Like I said, I'm very picky :stuck_out_tongue: 

Regarding your translation question from Discord: I've had a few people ask about this. The problem right now is that all of the strings are hardcoded, so translations aren't really possible. At some point I need to separate all of the UI strings into an array, shared across platforms, that can be easily swapped out for a translated array.

**Comment by Kazevic** [comment]
I screwed some things up (e.g. I forgot to move the "building for X" part) and I understand your statements. What do you think of it now?

**Comment by Hydr8gon** [comment]
I'm still unsure about some things:
- I think the usage section should stay after the downloads section, because using is the next step after downloading (building can stay below that, since it's less relevant for most users)
- The emulator should be referred to as 'NooDS' instead of 'it' the first time it's mentioned in a paragraph, just so the subject is established
- "You'll need to manually change the save type until it does if you load a new game and saving does not work." - This is worded strangely; the idea of saving not working should be mentioned before saying "until it does"

**Comment by Kazevic** [comment]
Alright, it should be good to go now.

**Pull request merged**
